# Generated by Django 6.0.1 on 2026-02-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_plannerhistory'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plannerhistory',
            new_name='core_planne_user_id_bd7ce9_idx',
            old_name='core_planne_user_id_6eba0f_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerhistory',
            new_name='core_planne_session_5a6034_idx',
            old_name='core_planne_session_dd5f95_idx',
        ),
        migrations.RenameIndex(
            model_name='plannerhistory',
            new_name='core_planne_event_t_3f5c0c_idx',
            old_name='core_planne_event_t_c56be5_idx',
        ),
    ]
